###
// Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "grzegorzpaluch.krk@gmail.com",
    "password": "123123"
}
###
// Me 
GET http://localhost:5000/me



// Logout
###
DELETE http://localhost:5000/logout
###
// Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Grzegorz",
    "surname": "Paluch",
    "street": "Kasztanowa",
    "houseNumber": "6",
    "city": "Kraków",
    "postCode": "32-087",
    "sex": "Mężczyzna",
    "phoneNumber": "794999310",
    "email": "grzegorzpaluch.krk@gmail.com",
    "role": "admin",
    "status": "true",
    "password": "123123",
    "confPassword": "123123"
}
###
// Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Grzegoasdrz",
    "surname": "Paluasdch",
    "street": "Kasztaasdnowa",
    "houseNumber": "6",
    "city": "Kraków",
    "postCode": "32-087",
    "sex": "Mężczyzna",
    "phoneNumber": "794999310",
    "email": "grzegorzpaluasdasdch.krk@gmail.com",
    "role": "admin",
    "status": "true",
    "password": "123123",
    "confPassword": "123123"
}
###
# // Create a communique
# POST http://localhost:5000/communique
# Content-Type: application/json

# {
#     "title": "Orlen flota 3 ",
#     "text": "raz dwa trzy 3 "
# }



###
// Create a agreement
POST http://localhost:5000/agreement
Content-Type: application/json

{
    "startContract": "2022-05-19",
    "endContract": "2022-05-20",
    "position": "kierowca",
    "typeContract": "umowa zlcenie"
            
}

###

// Get ALL users
GET http://localhost:5000/users


###
// Get SINGLE user
GET http://localhost:5000/users/e704427f-64a4-41cd-b3b5-74d0ce3938c3

###

// Update user

PATCH  http://localhost:5000/users/440015ff-3601-49cd-a5dd-b5d6e45fa9d7
Content-Type: application/json

{
    "name": "Alicja",
    "email": "alicja@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

###

// DELETE A USER 
DELETE  http://localhost:5000/users/c593b2a3-2523-469d-b6db-04f682a1cdfb


###
// Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "alicja@gmail.com",
    "password": "123123"
}
###
// Me 
GET http://localhost:5000/me



// Logout
###
DELETE http://localhost:5000/logout


# // Get All Products
# ###
# Get http://localhost:5000/products

# // Get One Product
# ###
# Get http://localhost:5000/products/bc952083-63a5-4e58-956e-25ab4e3bed53

# // POST data product
# ###
# POST http://localhost:5000/products
# Content-Type: application/json

# {
#     "name": "Trasa 4",
#     "price": 1231223
# }

# // UPDATE data product
# ###
# PATCH http://localhost:5000/products/bc952083-63a5-4e58-956e-25ab4e3bed53
# Content-Type: application/json

# {
#     "name": "Trasa UPDATE4",
#     "price": 1231223
# }

# // DELETE data product
# ###
# DELETE  http://localhost:5000/products/bc952083-63a5-4e58-956e-25ab4e3bed53
